// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: rag.sql

package rag_repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
	"github.com/pgvector/pgvector-go"
)

const searchDocumentChunks = `-- name: SearchDocumentChunks :many
SELECT
    id,
    page_number,
    chunk_index,
    content,
    created_at,
    1 - (embedding <=> $1) AS similarity
FROM document_chunks
ORDER BY embedding <=> $1
LIMIT $2
`

type SearchDocumentChunksParams struct {
	Embedding pgvector.Vector
	Limit     int32
}

type SearchDocumentChunksRow struct {
	ID         pgtype.UUID
	PageNumber pgtype.Int4
	ChunkIndex int32
	Content    string
	CreatedAt  pgtype.Timestamptz
	Similarity int32
}

func (q *Queries) SearchDocumentChunks(ctx context.Context, arg SearchDocumentChunksParams) ([]SearchDocumentChunksRow, error) {
	rows, err := q.db.Query(ctx, searchDocumentChunks, arg.Embedding, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SearchDocumentChunksRow
	for rows.Next() {
		var i SearchDocumentChunksRow
		if err := rows.Scan(
			&i.ID,
			&i.PageNumber,
			&i.ChunkIndex,
			&i.Content,
			&i.CreatedAt,
			&i.Similarity,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
