// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: chat.sql

package chat_repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
	"github.com/pgvector/pgvector-go"
)

const createNewMessage = `-- name: CreateNewMessage :exec
INSERT INTO messages (role,content,embedding)
VALUES ($1,$2,$3)
`

type CreateNewMessageParams struct {
	Role      string
	Content   string
	Embedding pgvector.Vector
}

func (q *Queries) CreateNewMessage(ctx context.Context, arg CreateNewMessageParams) error {
	_, err := q.db.Exec(ctx, createNewMessage, arg.Role, arg.Content, arg.Embedding)
	return err
}

const getLatestMessages = `-- name: GetLatestMessages :many
SELECT
  role,
  content,
  created_at
FROM messages
ORDER BY created_at DESC
LIMIT $1
`

type GetLatestMessagesRow struct {
	Role      string
	Content   string
	CreatedAt pgtype.Timestamptz
}

func (q *Queries) GetLatestMessages(ctx context.Context, limit int32) ([]GetLatestMessagesRow, error) {
	rows, err := q.db.Query(ctx, getLatestMessages, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetLatestMessagesRow
	for rows.Next() {
		var i GetLatestMessagesRow
		if err := rows.Scan(&i.Role, &i.Content, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMessagesBefore = `-- name: GetMessagesBefore :many
SELECT 
  role, 
  content,
  created_at
FROM messages
WHERE created_at < $1
ORDER BY id DESC
LIMIT $2
`

type GetMessagesBeforeParams struct {
	CreatedAt pgtype.Timestamptz
	Limit     int32
}

type GetMessagesBeforeRow struct {
	Role      string
	Content   string
	CreatedAt pgtype.Timestamptz
}

func (q *Queries) GetMessagesBefore(ctx context.Context, arg GetMessagesBeforeParams) ([]GetMessagesBeforeRow, error) {
	rows, err := q.db.Query(ctx, getMessagesBefore, arg.CreatedAt, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetMessagesBeforeRow
	for rows.Next() {
		var i GetMessagesBeforeRow
		if err := rows.Scan(&i.Role, &i.Content, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchSimilarMessages = `-- name: SearchSimilarMessages :many
SELECT
  role,
  content,
  created_at
FROM messages
WHERE embedding IS NOT NULL
ORDER BY embedding <=> $1
LIMIT $2
`

type SearchSimilarMessagesParams struct {
	Embedding pgvector.Vector
	Limit     int32
}

type SearchSimilarMessagesRow struct {
	Role      string
	Content   string
	CreatedAt pgtype.Timestamptz
}

func (q *Queries) SearchSimilarMessages(ctx context.Context, arg SearchSimilarMessagesParams) ([]SearchSimilarMessagesRow, error) {
	rows, err := q.db.Query(ctx, searchSimilarMessages, arg.Embedding, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SearchSimilarMessagesRow
	for rows.Next() {
		var i SearchSimilarMessagesRow
		if err := rows.Scan(&i.Role, &i.Content, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
