// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: chat.sql

package chat_repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
	"github.com/pgvector/pgvector-go"
)

const createNewMessage = `-- name: CreateNewMessage :exec
INSERT INTO messages (role,content,embedding)
VALUES ($1,$2,$3)
`

type CreateNewMessageParams struct {
	Role      string
	Content   string
	Embedding pgvector.Vector
}

func (q *Queries) CreateNewMessage(ctx context.Context, arg CreateNewMessageParams) error {
	_, err := q.db.Exec(ctx, createNewMessage, arg.Role, arg.Content, arg.Embedding)
	return err
}

const createNewMessageReturningID = `-- name: CreateNewMessageReturningID :one
INSERT INTO messages (role,content,embedding)
VALUES ($1,$2,$3)
RETURNING id
`

type CreateNewMessageReturningIDParams struct {
	Role      string
	Content   string
	Embedding pgvector.Vector
}

func (q *Queries) CreateNewMessageReturningID(ctx context.Context, arg CreateNewMessageReturningIDParams) (int32, error) {
	row := q.db.QueryRow(ctx, createNewMessageReturningID, arg.Role, arg.Content, arg.Embedding)
	var id int32
	err := row.Scan(&id)
	return id, err
}

const getDocumentNamesByMessageID = `-- name: GetDocumentNamesByMessageID :many
SELECT dc.document_name
FROM message_document_chunks mdc
JOIN document_chunks dc ON dc.id = mdc.chunk_id
WHERE mdc.message_id = $1
ORDER BY dc.document_name ASC
`

func (q *Queries) GetDocumentNamesByMessageID(ctx context.Context, messageID int32) ([]string, error) {
	rows, err := q.db.Query(ctx, getDocumentNamesByMessageID, messageID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var document_name string
		if err := rows.Scan(&document_name); err != nil {
			return nil, err
		}
		items = append(items, document_name)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getLatestMessages = `-- name: GetLatestMessages :many
SELECT id, role, content, created_at
FROM (
  SELECT
    id,
    role,
    content,
    created_at
  FROM messages
  ORDER BY created_at DESC
  LIMIT $1
) AS latest
ORDER BY created_at ASC
`

type GetLatestMessagesRow struct {
	ID        int32
	Role      string
	Content   string
	CreatedAt pgtype.Timestamptz
}

func (q *Queries) GetLatestMessages(ctx context.Context, limit int32) ([]GetLatestMessagesRow, error) {
	rows, err := q.db.Query(ctx, getLatestMessages, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetLatestMessagesRow
	for rows.Next() {
		var i GetLatestMessagesRow
		if err := rows.Scan(
			&i.ID,
			&i.Role,
			&i.Content,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMessagesBefore = `-- name: GetMessagesBefore :many
SELECT id, role, content, created_at
FROM (
  SELECT
    id,
    role,
    content,
    created_at
  FROM messages
  WHERE created_at < $1
  ORDER BY created_at DESC
  LIMIT $2
) AS messages_page
ORDER BY created_at ASC
`

type GetMessagesBeforeParams struct {
	CreatedAt pgtype.Timestamptz
	Limit     int32
}

type GetMessagesBeforeRow struct {
	ID        int32
	Role      string
	Content   string
	CreatedAt pgtype.Timestamptz
}

func (q *Queries) GetMessagesBefore(ctx context.Context, arg GetMessagesBeforeParams) ([]GetMessagesBeforeRow, error) {
	rows, err := q.db.Query(ctx, getMessagesBefore, arg.CreatedAt, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetMessagesBeforeRow
	for rows.Next() {
		var i GetMessagesBeforeRow
		if err := rows.Scan(
			&i.ID,
			&i.Role,
			&i.Content,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertMessageDocumentChunk = `-- name: InsertMessageDocumentChunk :exec
INSERT INTO message_document_chunks (message_id, chunk_id)
VALUES ($1, $2)
ON CONFLICT DO NOTHING
`

type InsertMessageDocumentChunkParams struct {
	MessageID int32
	ChunkID   pgtype.UUID
}

func (q *Queries) InsertMessageDocumentChunk(ctx context.Context, arg InsertMessageDocumentChunkParams) error {
	_, err := q.db.Exec(ctx, insertMessageDocumentChunk, arg.MessageID, arg.ChunkID)
	return err
}

const searchSimilarMessages = `-- name: SearchSimilarMessages :many
SELECT
  role,
  content,
  created_at
FROM messages
WHERE embedding IS NOT NULL
ORDER BY embedding <=> $1
LIMIT $2
`

type SearchSimilarMessagesParams struct {
	Embedding pgvector.Vector
	Limit     int32
}

type SearchSimilarMessagesRow struct {
	Role      string
	Content   string
	CreatedAt pgtype.Timestamptz
}

func (q *Queries) SearchSimilarMessages(ctx context.Context, arg SearchSimilarMessagesParams) ([]SearchSimilarMessagesRow, error) {
	rows, err := q.db.Query(ctx, searchSimilarMessages, arg.Embedding, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SearchSimilarMessagesRow
	for rows.Next() {
		var i SearchSimilarMessagesRow
		if err := rows.Scan(&i.Role, &i.Content, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
