// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package chat_repository

import (
	"github.com/jackc/pgx/v5/pgtype"
	"github.com/pgvector/pgvector-go"
)

type DocumentChunk struct {
	ID           pgtype.UUID
	DocumentName string
	ChunkIndex   int32
	Content      string
	Embedding    pgvector.Vector
	CreatedAt    pgtype.Timestamptz
}

type Message struct {
	ID        int32
	Role      string
	Content   string
	Embedding pgvector.Vector
	CreatedAt pgtype.Timestamptz
}
